dataset_root: D:/dataset/CSL/PHOENIX-2014/phoenix2014-release/phoenix-2014-multisigner
dict_path: ./preprocess/phoenix2014/gloss_dict.npy
evaluation_dir: ./evaluation/slr_eval
evaluation_prefix: phoenix2014-groundtruth
