dataset_root: D:/dataset/CSL/PHOENIX-2014-T-release-v3/PHOENIX-2014-T
dict_path: preprocess/phoenix2014-T/gloss_dict.npy
evaluation_dir: evaluation/slr_eval
evaluation_prefix: phoenix2014-T-groundtruth
